---
title: Sinetris's viewpoints
baseURL: https://sinetris.info/
defaultContentLanguage: en

theme:
  - github.com/sinetris/sine-die

module:
  hugoVersion:
    extended: true
    min: "0.158.0"

markup:
  highlight:
    noClasses: false
    lineNos: true
    lineNumbersInTable: false
  goldmark:
    parser:
      attribute:
        block: true
        title: true
    renderer:
      unsafe: true

params:
  tagline: Pragmatic overviews by Duilio Ruggiero
  showSearchUI: true
  enableFavicons: true
  author:
    email: duilio@sinetris.info
    name: Duilio Ruggiero
    link: 'https://sinetris.info'
  license: CC-BY-4.0
  licenselink: https://github.com/sinetris/sinetris-website/blob/main/LICENSE-DOCS
  logo: images/sinetris-logo.svg
  # Theme configuration
  SineDie:
    SearchEngine: pagefind
    SidebarMenu:
      MaxLevels: 3
      PagesOrder: ByWeight

menus:
  main:
    - name: GitHub
      url: https://github.com/sinetris/
      weight: 110
      params:
        isExternalLink: true
        onlyVisualSign: true
        visualSign: github
        visualSignType: brand
    - name: LinkedIn
      url: https://www.linkedin.com/in/duilioruggiero/
      weight: 120
      params:
        isExternalLink: true
        onlyVisualSign: true
        visualSign: linkedin
        visualSignType: brand
