baseURL = 'https://sinetris.info/'
languageCode = 'en-us'
title = "Sinetris's viewpoints"
theme = 'sine-die'

[params]
subTitle = "Pragmatic overviews"

# License
license = "CC-BY-4.0"
licenselink = "https://github.com/sinetris/sinetris-website/blob/main/LICENSE-DOCS"
